//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorLogWeb.ErrorLogServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ErrorLogServices.IErrorLogWS")]
    public interface IErrorLogWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLogWS/WriteToLog", ReplyAction="http://tempuri.org/IErrorLogWS/WriteToLogResponse")]
        void WriteToLog(string applicationName, string message, string source, string stackTrack, string errorLogUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLogWS/WriteToLog", ReplyAction="http://tempuri.org/IErrorLogWS/WriteToLogResponse")]
        System.Threading.Tasks.Task WriteToLogAsync(string applicationName, string message, string source, string stackTrack, string errorLogUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLogWS/WriteToMessageLog", ReplyAction="http://tempuri.org/IErrorLogWS/WriteToMessageLogResponse")]
        void WriteToMessageLog(string applicationName, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLogWS/WriteToMessageLog", ReplyAction="http://tempuri.org/IErrorLogWS/WriteToMessageLogResponse")]
        System.Threading.Tasks.Task WriteToMessageLogAsync(string applicationName, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IErrorLogWSChannel : ErrorLogWeb.ErrorLogServices.IErrorLogWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErrorLogWSClient : System.ServiceModel.ClientBase<ErrorLogWeb.ErrorLogServices.IErrorLogWS>, ErrorLogWeb.ErrorLogServices.IErrorLogWS {
        
        public ErrorLogWSClient() {
        }
        
        public ErrorLogWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErrorLogWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLogWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLogWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteToLog(string applicationName, string message, string source, string stackTrack, string errorLogUrl) {
            base.Channel.WriteToLog(applicationName, message, source, stackTrack, errorLogUrl);
        }
        
        public System.Threading.Tasks.Task WriteToLogAsync(string applicationName, string message, string source, string stackTrack, string errorLogUrl) {
            return base.Channel.WriteToLogAsync(applicationName, message, source, stackTrack, errorLogUrl);
        }
        
        public void WriteToMessageLog(string applicationName, string message) {
            base.Channel.WriteToMessageLog(applicationName, message);
        }
        
        public System.Threading.Tasks.Task WriteToMessageLogAsync(string applicationName, string message) {
            return base.Channel.WriteToMessageLogAsync(applicationName, message);
        }
    }
}
